import db from '../db/connection.js';
import Job from '../models/Jobs.js';

const insertData = async () => {
    await db.dropDatabase();
    
    const jobs = [
            {
              jobID: 'JOB001',
              location: 'New York, NY',
              title: 'Software Engineer',
              listingDate: new Date(),
              category: 'IT',
              description: 'Develop and maintain web applications.',
              remote: 'Hybrid',
              company: 'Tech Solutions',
              skillsNeeded: ['JavaScript', 'React', 'Node.js'],
              employmentType: 'Full-time',
              experienceLevel: 'Mid-level',
              salaryRange: '100000-120000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)), //will set deadline one month after current date
              contactInformation: 'recruiting@techsolutions.com',
            },
            {
              jobID: 'JOB002',
              location: 'San Francisco, CA',
              title: 'Data Analyst',
              listingDate: new Date(),
              category: 'Data Science',
              description: 'Analyze and interpret complex data sets.',
              remote: 'Remote',
              company: 'Data Insights',
              skillsNeeded: ['SQL', 'Python', 'Tableau'],
              employmentType: 'Full-time',
              experienceLevel: 'Entry-level',
              salaryRange: '70000-90000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'hr@datainsights.com',
            },
            {
              jobID: 'JOB003',
              location: 'Boston, MA',
              title: 'Project Manager',
              listingDate: new Date(),
              category: 'Management',
              description: 'Oversee project planning and execution.',
              remote: 'On-site',
              company: 'Project Pros',
              skillsNeeded: ['Project Management', 'Agile', 'Scrum'],
              employmentType: 'Full-time',
              experienceLevel: 'Senior',
              salaryRange: '90000-110000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'apply@projectpros.com',
            },
            {
              jobID: 'JOB004',
              location: 'Remote',
              title: 'Graphic Designer',
              listingDate: new Date(),
              category: 'Design',
              description: 'Create visual concepts and graphics.',
              remote: 'Remote',
              company: 'Creative Studio',
              skillsNeeded: ['Adobe Photoshop', 'Illustrator', 'Creativity'],
              employmentType: 'Contract',
              experienceLevel: 'Mid-level',
              salaryRange: '50000-70000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 2)),
              contactInformation: 'jobs@creativestudio.com',
            },
            {
              jobID: 'JOB005',
              location: 'Austin, TX',
              title: 'Marketing Coordinator',
              listingDate: new Date(),
              category: 'Marketing',
              description: 'Assist in marketing campaigns and strategies.',
              remote: 'Hybrid',
              company: 'Market Masters',
              skillsNeeded: ['SEO', 'Content Creation', 'Social Media'],
              employmentType: 'Part-time',
              experienceLevel: 'Entry-level',
              salaryRange: '40000-50000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'marketing@marketmasters.com',
            },
            {
              jobID: 'JOB006',
              location: 'Chicago, IL',
              title: 'Network Engineer',
              listingDate: new Date(),
              category: 'IT',
              description: 'Manage and maintain network infrastructure.',
              remote: 'On-site',
              company: 'NetSecure',
              skillsNeeded: ['Networking', 'Cisco', 'Security'],
              employmentType: 'Full-time',
              experienceLevel: 'Mid-level',
              salaryRange: '80000-100000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'careers@netsecure.com',
            },
            {
              jobID: 'JOB007',
              location: 'Seattle, WA',
              title: 'HR Specialist',
              listingDate: new Date(),
              category: 'Human Resources',
              description: 'Manage employee relations and HR policies.',
              remote: 'Hybrid',
              company: 'People Partners',
              skillsNeeded: ['HR Policies', 'Employee Relations', 'Recruitment'],
              employmentType: 'Full-time',
              experienceLevel: 'Mid-level',
              salaryRange: '60000-80000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 2)),
              contactInformation: 'hr@peoplepartners.com',
            },
            {
              jobID: 'JOB008',
              location: 'Denver, CO',
              title: 'Financial Analyst',
              listingDate: new Date(),
              category: 'Finance',
              description: 'Analyze financial data and trends.',
              remote: 'On-site',
              company: 'Finance First',
              skillsNeeded: ['Excel', 'Financial Modeling', 'Data Analysis'],
              employmentType: 'Full-time',
              experienceLevel: 'Mid-level',
              salaryRange: '75000-95000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'financejobs@financefirst.com',
            },
            {
              jobID: 'JOB009',
              location: 'Miami, FL',
              title: 'Sales Executive',
              listingDate: new Date(),
              category: 'Sales',
              description: 'Drive sales and manage client relationships.',
              remote: 'Hybrid',
              company: 'Sales Success',
              skillsNeeded: ['Sales', 'CRM', 'Customer Service'],
              employmentType: 'Full-time',
              experienceLevel: 'Senior',
              salaryRange: '80000-120000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'sales@salesuccess.com',
            },
            {
              jobID: 'JOB010',
              location: 'Remote',
              title: 'Content Writer',
              listingDate: new Date(),
              category: 'Content',
              description: 'Write and edit content for various platforms.',
              remote: 'Remote',
              company: 'Content Creators',
              skillsNeeded: ['Writing', 'Editing', 'SEO'],
              employmentType: 'Contract',
              experienceLevel: 'Mid-level',
              salaryRange: '40000-60000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 2)),
              contactInformation: 'jobs@contentcreators.com',
            },
            {
              jobID: 'JOB011',
              location: 'Los Angeles, CA',
              title: 'UI/UX Designer',
              listingDate: new Date(),
              category: 'Design',
              description: 'Design user interfaces and user experiences.',
              remote: 'On-site',
              company: 'DesignHub',
              skillsNeeded: ['UI/UX Design', 'Wireframing', 'User Testing'],
              employmentType: 'Full-time',
              experienceLevel: 'Mid-level',
              salaryRange: '90000-110000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'careers@designhub.com',
            },
            {
              jobID: 'JOB012',
              location: 'Dallas, TX',
              title: 'IT Support Specialist',
              listingDate: new Date(),
              category: 'IT',
              description: 'Provide technical support to end-users.',
              remote: 'On-site',
              company: 'TechSupport',
              skillsNeeded: ['Troubleshooting', 'Customer Support', 'Windows OS'],
              employmentType: 'Full-time',
              experienceLevel: 'Entry-level',
              salaryRange: '50000-60000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'support@techsupport.com',
            },
            {
              jobID: 'JOB013',
              location: 'Atlanta, GA',
              title: 'Product Manager',
              listingDate: new Date(),
              category: 'Management',
              description: 'Lead product development and strategy.',
              remote: 'Hybrid',
              company: 'ProductPulse',
              skillsNeeded: ['Product Management', 'Agile', 'Leadership'],
              employmentType: 'Full-time',
              experienceLevel: 'Senior',
              salaryRange: '110000-130000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'jobs@productpulse.com',
            },
            {
              jobID: 'JOB014',
              location: 'Washington, DC',
              title: 'Legal Assistant',
              listingDate: new Date(),
              category: 'Legal',
              description: 'Assist lawyers with case preparation and research.',
              remote: 'On-site',
              company: 'Law Associates',
              skillsNeeded: ['Legal Research', 'Document Drafting', 'Client Interaction'],
              employmentType: 'Part-time',
              experienceLevel: 'Entry-level',
              salaryRange: '40000-50000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'apply@lawassociates.com',
            },
            {
              location: 'Los Angeles, CA',
              title: 'UX Designer',
              listingDate: new Date(),
              category: 'Design',
              description: 'Design user-friendly interfaces and experiences.',
              remote: 'Hybrid',
              company: 'Design Innovations',
              skillsNeeded: ['UI/UX Design', 'Wireframing', 'Prototyping'],
              employmentType: 'Full-time',
              experienceLevel: 'Mid-level',
              salaryRange: '70000-90000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 2)),
              contactInformation: 'jobs@designinnovations.com',
          },
          {
              location: 'Denver, CO',
              title: 'Cybersecurity Specialist',
              listingDate: new Date(),
              category: 'IT',
              description: 'Implement and monitor security measures.',
              remote: 'On-site',
              company: 'SecureTech',
              skillsNeeded: ['Cybersecurity', 'Penetration Testing', 'Risk Assessment'],
              employmentType: 'Full-time',
              experienceLevel: 'Senior',
              salaryRange: '120000-140000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'careers@securetech.com',
          },
          {
              location: 'New York, NY',
              title: 'Content Strategist',
              listingDate: new Date(),
              category: 'Marketing',
              description: 'Develop and manage content strategies.',
              remote: 'Remote',
              company: 'Creative Media',
              skillsNeeded: ['Content Strategy', 'SEO', 'Copywriting'],
              employmentType: 'Contract',
              experienceLevel: 'Mid-level',
              salaryRange: '60000-80000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'hr@creativemedia.com',
          },
          {
              location: 'Austin, TX',
              title: 'Customer Support Representative',
              listingDate: new Date(),
              category: 'Customer Service',
              description: 'Provide support to customers and resolve their issues.',
              remote: 'Hybrid',
              company: 'CustomerFirst',
              skillsNeeded: ['Communication', 'Problem-solving', 'CRM'],
              employmentType: 'Part-time',
              experienceLevel: 'Entry-level',
              salaryRange: '35000-45000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'support@customerfirst.com',
          },
          {
              location: 'Boston, MA',
              title: 'Data Engineer',
              listingDate: new Date(),
              category: 'Data Science',
              description: 'Design and maintain data pipelines.',
              remote: 'On-site',
              company: 'DataFlow',
              skillsNeeded: ['Python', 'SQL', 'Data Warehousing'],
              employmentType: 'Full-time',
              experienceLevel: 'Mid-level',
              salaryRange: '110000-130000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'careers@dataflow.com',
          },
          {
              location: 'Remote',
              title: 'Digital Marketing Specialist',
              listingDate: new Date(),
              category: 'Marketing',
              description: 'Plan and execute digital marketing campaigns.',
              remote: 'Remote',
              company: 'MarketOnline',
              skillsNeeded: ['SEO', 'PPC', 'Social Media Marketing'],
              employmentType: 'Full-time',
              experienceLevel: 'Entry-level',
              salaryRange: '50000-70000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'jobs@marketonline.com',
          },
          {
              location: 'Chicago, IL',
              title: 'Full-Stack Developer',
              listingDate: new Date(),
              category: 'IT',
              description: 'Develop and maintain web applications.',
              remote: 'Hybrid',
              company: 'WebTech Solutions',
              skillsNeeded: ['JavaScript', 'React', 'Node.js'],
              employmentType: 'Full-time',
              experienceLevel: 'Mid-level',
              salaryRange: '100000-120000 USD',
              applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
              contactInformation: 'careers@webtechsolutions.com',
          },
          {
            location: 'Los Angeles, CA',
            title: 'UX Designer',
            listingDate: new Date(),
            category: 'Design',
            description: 'Create intuitive user interfaces and experiences.',
            remote: 'Hybrid',
            company: 'Design Innovations',
            skillsNeeded: ['UI/UX Design', 'Figma', 'Prototyping'],
            employmentType: 'Full-time',
            experienceLevel: 'Senior',
            salaryRange: '85000-105000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 2)),
            contactInformation: 'jobs@designinnovations.com',
        },
        {
            location: 'Denver, CO',
            title: 'Cybersecurity Specialist',
            listingDate: new Date(),
            category: 'IT',
            description: 'Secure IT infrastructure and prevent cyber threats.',
            remote: 'On-site',
            company: 'SecureTech',
            skillsNeeded: ['Cybersecurity', 'Network Security', 'Incident Response'],
            employmentType: 'Full-time',
            experienceLevel: 'Mid-level',
            salaryRange: '115000-135000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'careers@securetech.com',
        },
        {
            location: 'New York, NY',
            title: 'Content Strategist',
            listingDate: new Date(),
            category: 'Marketing',
            description: 'Develop content strategies for digital marketing.',
            remote: 'Remote',
            company: 'Creative Media',
            skillsNeeded: ['Content Strategy', 'SEO', 'Content Management Systems'],
            employmentType: 'Contract',
            experienceLevel: 'Mid-level',
            salaryRange: '62000-82000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'hr@creativemedia.com',
        },
        {
            location: 'Austin, TX',
            title: 'Customer Support Representative',
            listingDate: new Date(),
            category: 'Customer Service',
            description: 'Handle customer inquiries and complaints efficiently.',
            remote: 'Hybrid',
            company: 'CustomerFirst',
            skillsNeeded: ['Communication', 'Technical Support', 'Problem-solving'],
            employmentType: 'Part-time',
            experienceLevel: 'Entry-level',
            salaryRange: '36000-46000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'support@customerfirst.com',
        },
        {
            location: 'Boston, MA',
            title: 'Data Engineer',
            listingDate: new Date(),
            category: 'Data Science',
            description: 'Build and maintain scalable data pipelines.',
            remote: 'On-site',
            company: 'DataFlow',
            skillsNeeded: ['Python', 'SQL', 'ETL'],
            employmentType: 'Full-time',
            experienceLevel: 'Senior',
            salaryRange: '115000-135000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'careers@dataflow.com',
        },
        {
            location: 'Remote',
            title: 'Digital Marketing Specialist',
            listingDate: new Date(),
            category: 'Marketing',
            description: 'Optimize digital marketing strategies and campaigns.',
            remote: 'Remote',
            company: 'MarketOnline',
            skillsNeeded: ['SEO', 'Google Analytics', 'Social Media Marketing'],
            employmentType: 'Full-time',
            experienceLevel: 'Entry-level',
            salaryRange: '52000-72000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'jobs@marketonline.com',
        },
        {
            location: 'Chicago, IL',
            title: 'Full-Stack Developer',
            listingDate: new Date(),
            category: 'IT',
            description: 'Full stack development of web applications.',
            remote: 'Hybrid',
            company: 'WebTech Solutions',
            skillsNeeded: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
            employmentType: 'Full-time',
            experienceLevel: 'Mid-level',
            salaryRange: '105000-125000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'careers@webtechsolutions.com',
        },
        {
            location: 'New York, NY',
            title: 'HR Specialist',
            listingDate: new Date(),
            category: 'Human Resources',
            description: 'Oversee HR functions including recruitment and compliance.',
            remote: 'Hybrid',
            company: 'HR Solutions',
            skillsNeeded: ['HR Policies', 'Recruitment', 'Employee Relations'],
            employmentType: 'Full-time',
            experienceLevel: 'Mid-level',
            salaryRange: '75000-95000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'hr@hrsolutions.com',
        },
        {
            location: 'Boston, MA',
            title: 'Data Engineer',
            listingDate: new Date(),
            category: 'Data Science',
            description: 'Develop and optimize data architectures.',
            remote: 'On-site',
            company: 'DataFlow',
            skillsNeeded: ['Python', 'Big Data', 'Data Warehousing'],
            employmentType: 'Full-time',
            experienceLevel: 'Mid-level',
            salaryRange: '100000-120000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'careers@dataflow.com',
        },
        {
            location: 'San Francisco, CA',
            title: 'Data Analyst',
            listingDate: new Date(),
            category: 'Data Science',
            description: 'Perform data analysis and generate reports.',
            remote: 'On-site',
            company: 'Data Insights',
            skillsNeeded: ['Data Analysis', 'SQL', 'Data Visualization'],
            employmentType: 'Full-time',
            experienceLevel: 'Mid-level',
            salaryRange: '75000-95000 USD',
            applicationDeadline: new Date(new Date().setMonth(new Date().getMonth() + 1)),
            contactInformation: 'hr@datainsights.com',
        }
    ]

    await Job.insertMany(jobs);
    console.log("Jobs created")

    db.close();
}

insertData()